### MCP capabilities request
POST http://localhost:5280/mcp
Content-Type: application/json
Accept: application/json, text/event-stream
MCP-Protocol-Version: 2024-11-05

{
  "jsonrpc": "2.0",
  "id": "1",
  "method": "tools/list",
  "params": {}
}

### Upsert (add) an animal
POST http://localhost:5280/mcp
Content-Type: application/json
Accept: application/json, text/event-stream
MCP-Protocol-Version: 2024-11-05

{
  "jsonrpc": "2.0",
  "id": "1",
  "method": "tools/call",
  "params": {
    "name": "upsert_animal",
    "arguments": {
      "animal": {
        "id": 1,
        "type": "Cat",
        "name": "Misty",
        "age": 3
      }
    }
  }
}

### Get by name
POST http://localhost:5280/mcp
Content-Type: application/json
Accept: application/json, text/event-stream
MCP-Protocol-Version: 2024-11-05

{
  "jsonrpc": "2.0",
  "id": "22",
  "method": "tools/call",
  "params": {
    "name": "get_animal_by_name",
    "arguments": { "name": "Misty" }
  }
}

### List all
POST http://localhost:5280/mcp
Content-Type: application/json
Accept: application/json, text/event-stream
MCP-Protocol-Version: 2024-11-05

{
  "jsonrpc": "2.0",
  "id": "3",
  "method": "tools/call",
  "params": {
    "name": "get_all_animals",
    "arguments": {}
  }
}

### Echo test
POST http://localhost:5280/mcp
Content-Type: application/json
Accept: application/json, text/event-stream
MCP-Protocol-Version: 2024-11-05

{
  "jsonrpc": "2.0",
  "id": "4",
  "method": "tools/call",
  "params": {
    "name": "echo",
    "arguments": { "message": "hello from .http" }
  }
}